server {
  host = "localhost"
  port = 8080
},
db {
  url = "jdbc:postgresql://localhost:5432/pekko_db"
  user = "postgres"
  password = "root"
  driver = "org.postgresql.Driver"
  connectionPool = "HikariCP"
  numThreads = 10
}